export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";
export const USER_SIGNOUT = "USER_SIGNOUT";

export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";

export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAIL = "USER_PROFILE_FAIL";

export const USER_FOLLOW_REQUEST = "USER_FOLLOW_REQUEST";
export const USER_FOLLOW_SUCCESS = "USER_FOLLOW_SUCCESS";
export const USER_FOLLOW_FAIL = "USER_FOLLOW_FAIL";

export const USER_UNFOLLOW_REQUEST = "USER_UNFOLLOW_REQUEST";
export const USER_UNFOLLOW_SUCCESS = "USER_UNFOLLOW_SUCCESS";
export const USER_UNFOLLOW_FAIL = "USER_UNFOLLOW_FAIL";

export const USER_SEARCHING = "USER_SEARCHING";

export const USER_REQUEST_RESET_PASSWORD = "USER_REQUEST_RESET_PASSWORD";
export const USER_FAIL_RESET_PASSWORD = "USER_FAIL_RESET_PASSWORD";

export const USER_UPDATE_PASSWORD_SUCCESS = "USER_UPDATE_PASSWORD_SUCCESS";
export const USER_UPDATE_PASSWORD_FAIL = "USER_UPDATE_PASSWORD_FAIL";

export const USER_UPDATED = "USER_UPDATED";
export const RESET_STATE = "RESET_STATE";
export const CHECK_TOKEN = "CHECK_TOKEN";

export const USER_UPLOAD_PROFILE_SUCCESS = "USER_UPLOAD_PROFILE_SUCCESS";
export const USER_UPLOAD_PROFILE_FAIL = "USER_UPLOAD_PROFILE_FAIL";
